apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-ai.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sentinel-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
